---
- name: RUNNING HEALTH-CHECK COMMANDS FROM NSO 
  hosts: 
    - localhost
  gather_facts: no
  connection: local

  roles: 
    - ops_show_state
    - ops_show_block 
    - ops_show_cpu
    - ops_show_capture
    - ops_show_asp_drop
    - ops_show_svc_policy