---
- name: RUNNING HEALTH-CHECK COMMANDS FROM NSO 
  hosts: 
    - localhost
  gather_facts: no
  connection: local

  roles: 
    - { role: ops_show_state }
    - { role: ops_show_block }
    - { role: ops_show_cpu }
    - { role: ops_show_capture }
    - { role: ops_show_asp_drop }
    - { role: ops_show_svc_policy }