---
# tasks file for ops_show_asp_drop

- name: SHOW ASP DROP INFORMATION FROM NSO
  nso_action:
    url: "{{ nso.nso_url}}"
    username: "{{ nso.nso_username }}"
    password: "{{ nso.nso_api_password }}"
    path: '/ncs:devices/device{sjc02-wxqa-asa01a.webex.com}/live-status/asa-stats:exec/any'
    input: {context: "Core", auto-prompts: [], args: ["show asp drop"]}
  register: nso_results6

- debug: 
    var: nso_results6.output.result
