---
# tasks file for ops_show_capture
- name: LOAD "qa_lab_hosts" VAR WITH A LIST OF LAB HOSTS
  set_fact:
    qa_lab_hosts: "{{ groups['nso-qa-asa'] }}"
  register: qa_lab_hosts

- name: LOOP over included tasks
  include_tasks: show_asp.yml
  loop: "{{ qa_lab_hosts }}"
