---
# included file for show version
- name: SHOW VERSION FROM NSO 
  nso_action:
    url: "{{ nso.nso_url}}"
    username: "{{ nso.nso_username }}"
    password: "{{ nso.nso_api_password }}"
    path: '/ncs:devices/device{"{{item}}"}/live-status/asa-stats:exec/show'
    input: {args: ["version"]}
  register: nso_results
  changed_when: False

- debug: 
    var: nso_results.output