---
# tasks file for exp_ct
- name: READ ASA CONFIG FILE in JSON format
  shell: cat "./host_vars/{{item}}/nso_{{item}}.json"
  register: asa_conf

- name: STORE CONFIG IN A VARIABLE
  set_fact: inp={{ asa_conf.stdout }}

- name: CREATE a FILE to WRITE CONTEXTS for EACH ASA
  file:
    path: "./host_vars/{{item}}/extracted_context.yml"
    state: touch
    mode: 0777
  delegate_to: localhost

- name: WRITE CONTEXTS TO FILE
  lineinfile :
    dest: './host_vars/{{item}}/extracted_context.yml'
    line: "{{ line_item }}"
  with_items: 
    - "{{ inp | json_query('\"tailf-ncs:devices\".device[0].config.\"tailf-ned-cisco-asa:changeto\".context[].\"context-name\"') }} "
  loop_control:
    loop_var: line_item